-- Sections are no longer only grades: the teacher can add any book
-- ("Adults", "Summer Camp", ...) from the admin page.
alter table grades rename to books;
alter table artworks rename column grade_id to book_id;

alter table books add column sort_order integer;
update books set sort_order = id;
alter table books alter column sort_order set not null;

-- Auto-generate ids for teacher-created books; 100+ keeps clear of seeded grades
alter table books alter column id add generated by default as identity (start with 100);

-- Brighter blues/greens: the originals read as black under the warm scene light
update books set book_color = '#2b5288' where book_color = '#1e3a5f';
update books set book_color = '#3d7a52' where book_color = '#2d5a3d';
update books set book_color = '#9c2a2a' where book_color = '#7a1f1f';

create policy "teacher insert books" on books for insert to authenticated with check (true);
create policy "teacher delete books" on books for delete to authenticated using (true);

drop function search_artworks(text);
create function search_artworks(query text)
returns table (
  id uuid, title text, book_id smallint, book_label text,
  page_order integer, similarity real
)
language sql stable as $$
  select a.id, a.title, a.book_id, b.label, a.page_order,
         similarity(a.title, query) as similarity
  from artworks a
  join books b on b.id = a.book_id
  where a.title % query or a.title ilike '%' || query || '%'
  order by similarity desc
  limit 20;
$$;
